### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ricthomas** [eladnava/batch-reply-for-gmail#4]
Hello @eladnava 

Thinking would it be ok updating to jQuery version v1.11.1 --> 3.5.0?

**Comment by eladnava** [comment]
Hi @cybersecdev,
You're welcome to give it a try and see if the extension still works! If so, feel free to submit a PR.

**Comment by ricthomas** [comment]
Sure thing. Let me do that. Thanks!

**Comment by ricthomas** [comment]
I think I need access to pushing a change branch

**Comment by eladnava** [comment]
@cybersecdev you will need to first fork the repository to your own account, clone the forked repo to your desktop, make the changes into a new git branch, commit & push the branch to your own GitHub cloned project, then finally open a PR on this page:
https://github.com/eladnava/batch-reply-for-gmail/compare
